# Generated by Django 5.1.1 on 2025-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_is_scientist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
