# Generated by Django 5.1.1 on 2025-01-17 11:23

import s3_file_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_user_access_token_alter_user_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', s3_file_field.fields.S3FileField(blank=True, null=True)),
            ],
        ),
    ]
